services:
  protomock:
    image: skanukov/protomock:latest
    ports:
      - "8000:8000" # HTTP port
      - "8010:8010" # gRPC port
    volumes:
      - ./configs:/app/configs
      - ./mocks:/app/mocks
